#!/usr/bin/env bash

self_path="$(realpath $(dirname $0))"

case "$1" in
    "user" )
        shift
        home-manager -f "$self_path/users/$(whoami)/home.nix" switch "$@"
        ;;
    "system" )
        shift
        sudo nixos-rebuild -I nixos-config="$self_path/system/configuration.nix" switch "$@"
        ;;
    * )
        >&2 echo "Usage ${0##*/} <system|user>"
        ;;
esac
