#! /bin/sh

# shellcheck disable=SC3020,SC3028

#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          35
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  \#c2bdb2
bspc config focused_border_color \#494d78 #fe8019

bspc rule -a "Steam:*:Friends List" state=floating
bspc rule -a "ida64.exe:*:About" state=floating
bspc rule -a "ida64.exe:*:Please wait..." state=floating
bspc rule -a "ida64.exe:*:Information" state=floating

eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

"$HOME/.config/polybar/launch" &
pgrep -u $UID -x mpd  &>/dev/null || mpd &
pgrep -u $UID -x sxhkd  &>/dev/null || sxhkd &
pgrep -u $UID -x fcitx5 &>/dev/null || fcitx5 -d &
pgrep -u $UID -x dunst &>/dev/null || dunst &
# feh --bg-fill --no-fehbg $HOME/dot/papes/arch_gruvbox.png &
feh --bg-fill --no-fehbg "$HOME/dot/papes/cur.jpg" &
# feh --bg-scale --no-fehbg "$HOME/dot/papes/lofi-coffee.jpg" &
xsetroot -cursor_name left_ptr &
setxkbmap -option caps:ctrl_modifier &
